# fly.toml app configuration file generated for backend-iot2-divine-cloud-2666 on 2025-04-24T20:36:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-iot2-divine-cloud-2666'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
