CREATE TABLE SensorValues (
    created_at DATETIME PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
    temperature FLOAT NOT NULL,
    gas INTEGER NOT NULL,
    flame BOOLEAN NOT NULL
);

CREATE TABLE Risk(
    created_at DATETIME PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
    risk INTEGER NOT NULL
);