// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Risk struct {
	CreatedAt time.Time
	Risk      int64
}

type Sensorvalue struct {
	CreatedAt   time.Time
	Temperature float64
	Gas         int64
	Flame       bool
}
